#define m$message1              1
#define m$file_open             2
#define m$file_read             3
#define m$file_write            4
#define m$file_delete           5
#define m$file_close            6
#define m$net_send              7
#define m$net_recv              8
#define m$shmat                 9
#define m$shmget                10
#define m$shmctrl               11
#define m$shmdt                 12
#define m$ftok                  13
#define m$fork                  14
#define m$exec                  15
#define m$msgget                16
#define m$msgctrl               17
#define m$calloc                18
#define m$malloc                19
#define m$poll                  20
#define m$queue_open            21
#define m$start_station         22
#define m$abort_station         23
#define m$station_not_found     24
#define m$start_station_info    25
#define m$term_station_info     26
#define m$invalid_parameter     27
#define m$invalid_command       28
#define m$over_data             29
#define m$opendir               30
#define m$setlog                31
#define m$system                32
#define m$file_empty            33
#define m$chdir                 34
#define m$mkdir                 35
#define m$coredir               36
#define m$getenv                37
#define m$db_connect            38
#define m$db_err                39
#define m$start_process         40
#define m$stop_process          41
#define m$lpr_error             42
#define m$putenv                43
#define m$sql_statment          44
#define m$abend_process         45
#define m$unmatch_parameter_count 53
#define m$unknown_parameter     54
#define m$emb_error             55

#define m$MBB1000W  	      1000
#define m$MBB1001W            1001
#define m$roc_cont_no         1002
#define m$exist_contract_new  1004
#define m$no_exist_contract   1006
#define m$MBB1007W            1007
#define m$transfer_error      1010
#define m$MBB1012W            1012
#define m$MBB1013W            1013
#define m$MBB1014W            1014
#define m$MBB1025W            1025
#define m$MBB1026W            1026
#define m$MBB1027W            1027
#define m$MBB1028W            1028

#define m$data_not_found      1100 
#define m$rm_data_cnt         1101
#define m$rm_old_data         1102
#define m$analyze_table       1103
#define m$analyze_proceed     1104
#define m$analyze_count       1105
#define m$synonym_not_found   1106
#define m$invalid_synonym     1107
#define m$timeout             1108
#define m$over_tbs_utilization 1109
#define m$unmach_record_count 1110
#define m$update_contact_history_count 1112
#define m$drop_table 1113
#define m$deleted_id 1115
#define m$start_method 1116
#define m$stop_method 1117
#define m$error_method 1118
#define m$view_not_found   1119
#define m$invalid_view     1120
#define m$analyze_schema   1121
#define m$table_invalid    1122

#define m$MBB5001I            5001
#define m$MBB5002E            5002
#define m$MBB5003I            5003
#define m$row_count				5108

#define m$not_found_customer 7000
